/**
 * Download utilities for newsletter export
 */

interface NewsletterContent {
  title: string;
  tldr: string;
  core_issues: Array<{
    title: string;
    summary: string;
    links: Array<{ url: string; title: string }>;
  }>;
  deep_dive: {
    title: string;
    content: string;
    additional_readings: Array<{
      url: string;
      title: string;
      description?: string;
    }>;
  };
  next_questions: string[];
  sources: Array<{
    url: string;
    title: string;
    domain: string;
    accessed_at: string;
  }>;
}

/**
 * Convert newsletter content to Markdown format
 */
function newsletterToMarkdown(content: NewsletterContent): string {
  let markdown = `# ${content.title}\n\n`;

  // TL;DR
  markdown += `## 📝 TL;DR\n\n${content.tldr}\n\n`;

  // Core Issues
  markdown += `## 핵심 이슈\n\n`;
  content.core_issues.forEach((issue, index) => {
    markdown += `### ${index + 1}. ${issue.title}\n\n`;
    markdown += `${issue.summary}\n\n`;
    if (issue.links.length > 0) {
      markdown += `**관련 링크:**\n`;
      issue.links.forEach((link) => {
        markdown += `- [${link.title}](${link.url})\n`;
      });
      markdown += `\n`;
    }
  });

  // Deep Dive
  markdown += `## 🔍 Deep Dive: ${content.deep_dive.title}\n\n`;
  markdown += `${content.deep_dive.content}\n\n`;
  if (content.deep_dive.additional_readings.length > 0) {
    markdown += `**추가 읽을거리:**\n`;
    content.deep_dive.additional_readings.forEach((reading) => {
      markdown += `- [${reading.title}](${reading.url})`;
      if (reading.description) {
        markdown += ` - ${reading.description}`;
      }
      markdown += `\n`;
    });
    markdown += `\n`;
  }

  // Next Questions
  if (content.next_questions.length > 0) {
    markdown += `## 💡 다음에 파볼 질문\n\n`;
    content.next_questions.forEach((question) => {
      markdown += `- ${question}\n`;
    });
    markdown += `\n`;
  }

  // Sources
  if (content.sources.length > 0) {
    markdown += `## 📚 출처\n\n`;
    content.sources.forEach((source, index) => {
      markdown += `${index + 1}. [${source.title}](${source.url}) (${source.domain})\n`;
    });
    markdown += `\n`;
  }

  markdown += `---\n\n`;
  markdown += `*Generated by Automata - AI-powered personalized newsletters*\n`;

  return markdown;
}

/**
 * Download newsletter as Markdown file
 */
export function downloadAsMarkdown(
  content: NewsletterContent,
  filename?: string
) {
  const markdown = newsletterToMarkdown(content);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download =
    filename || `newsletter-${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download newsletter as PDF (requires jsPDF library)
 * Note: This is a placeholder for future PDF implementation with Korean font support
 */
export async function downloadAsPDF(
  content: NewsletterContent,
  filename?: string
) {
  // TODO: Implement PDF generation with Korean font support
  // This requires:
  // 1. jsPDF library
  // 2. Korean font file (e.g., NotoSansKR)
  // 3. Font registration with jsPDF
  // 4. Proper text wrapping and layout

  console.warn('PDF download is not yet implemented');

  // For now, fallback to Markdown download
  downloadAsMarkdown(content, filename);
}
