/**
 * Download utilities for newsletter export
 */

interface NewsletterContent {
  title: string;
  body: string;
  word_count?: number;
  estimated_reading_time?: number;
}

/**
 * Convert newsletter content to Markdown format
 */
function newsletterToMarkdown(content: NewsletterContent): string {
  let markdown = `# ${content.title}\n\n`;
  markdown += content.body;
  markdown += `\n\n---\n\n`;
  markdown += `*Generated by Automata - AI-powered personalized newsletters*\n`;
  return markdown;
}

/**
 * Download newsletter as Markdown file
 */
export function downloadAsMarkdown(
  content: NewsletterContent,
  filename?: string
) {
  const markdown = newsletterToMarkdown(content);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download =
    filename || `newsletter-${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download newsletter as PDF (requires jsPDF library)
 * Note: This is a placeholder for future PDF implementation with Korean font support
 */
export async function downloadAsPDF(
  content: NewsletterContent,
  filename?: string
) {
  // TODO: Implement PDF generation with Korean font support
  // This requires:
  // 1. jsPDF library
  // 2. Korean font file (e.g., NotoSansKR)
  // 3. Font registration with jsPDF
  // 4. Proper text wrapping and layout

  console.warn('PDF download is not yet implemented');

  // For now, fallback to Markdown download
  downloadAsMarkdown(content, filename);
}
